glasgow_untuned/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from glasuntu import views
from django.conf import settings
"""
having different namespaces for different apps (e.g. glasuntu and users)
lets you distinguish between the urls of your apps
"""
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('glasuntu.urls', namespace='glasuntu')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
]

glasuntu/urls.py
"""This file outlines the url patterns for Glasgow Untuned ('glasuntu')"""

from django.conf.urls import url #url function connects urls to views
from . import views

#urlpatterns contains list of page urls for Glasgow_Untuned
urlpatterns = [
	#Home - url function takes 3 arguments: regular expression (r'^$'), function to be called (views.index), url pattern name (index)
	url(r'^$', views.index, name='index'),
	
	#List - display search results
	url(r'^list/$', views.search, name='search'),
	
	#Artist page url
	url(r'^band/(?P<artist_id>\d+)/$', views.artist, name='artist'),
	
	#Venue page url
	url(r'^venue/(?P<venue_id>\d+)/$', views.venue, name="venue"),
	
	#Create artist page url
	url(r'^new_artist/$', views.new_artist, name = 'new_artist'),
	
	#Register venue page url
	url(r'^new_venue/$', views.new_venue, name = 'new_venue'),
	
	#User registration url
	url(r'^register/$', views.register, name='register'),
	
	#User login url
    url(r'^login/$', views.user_login, name='login'),
	
	#Logout page url
    url(r'^logout/$', views.user_logout, name='logout'),
	
	#Edit artist description url
	url(r'^edit_artist/(?P<artist_id>\d+)/$', views.edit_artist, name='edit_artist'),
	
	#Edit venue description url
	url(r'^edit_venue/(?P<venue_id>\d+)/$', views.edit_venue, name='edit_venue'),

        #likes
        url(r'^like_venue/$', views.like_venue, name='like_venue'),
]

glasuntu/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class VenuePage(models.Model):
	id = models.IntegerField(primary_key = True)
	name = models.CharField(max_length=200, default = "")
	owner = models.ForeignKey(User, default = 1)
	address = models.CharField(max_length=200, default = "")
	picture = models.CharField(max_length=400, default = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKh6zi1IdUc7vNzKuyCT_AgHj8GxpBUBjZ-0rCtk5GmSOJoMKjRQ")
	website = models.CharField(max_length=200, default = "")
	info = models.CharField(max_length=1000, default = "")
	genre = models.CharField(max_length=200, default = "")
	likes = models.IntegerField(default=0)
	def __str__(self):
		return self.name

class ArtistPage(models.Model):
	id = models.IntegerField(primary_key = True)
	name = models.CharField(unique=True, max_length=200)
	owner = models.ForeignKey(User, default = 1)
	picture = models.CharField(max_length=400, default = "https://ryanboudnotisahackdotcom.files.wordpress.com/2017/02/266c2fa0-9909-4e54-bb45-a4ef515e404f.jpg")
	website = models.CharField(max_length=200, default = "")
	info = models.CharField(max_length=1000, default = "")
	genre = models.CharField(max_length=200, default = "")
	def __str__(self):
		return self.name
		
class Genre(models.Model):
	name = models.CharField(max_length=50)
	def __str__(self):
		return self.name
		
class Event(models.Model):
	name = models.ForeignKey(ArtistPage, default = "")
	date = models.DateField(default = "")
	venue = models.ForeignKey(VenuePage, default = "")
	def __str__(self):
		return self.name
		
class UserProfile(models.Model):
	user = models.OneToOneField(User)
	picture = models.ImageField(upload_to='profile_images', blank=True)
	
	#override __unicode__()
	def __str__(self):
		return self.user.username

glasuntu/forms.py
from django import forms
from .models import ArtistPage
from .models import VenuePage
from .models import UserProfile
from django.contrib.auth.models import User

class ArtistPageForm(forms.ModelForm):
	class Meta:
		model = ArtistPage
		fields = ['name', 'website', 'info', 'genre']
		labels = {'name': 'Name:',
					'website': 'Website:',
					'info':'Description:',
					'genre':'Genre(s):'}
		widgets = {'info': forms.Textarea(attrs={'cols': 50})}
		
class VenuePageForm(forms.ModelForm):
	class Meta:
		model = VenuePage
		fields = ['name', 'address', 'website', 'info', 'genre']
		labels = {'name': 'Name:',
				'address': 'Address:',
				'website': 'Website:',
				'info':'Description:',
				'genre':'Genre(s):'
				}
		widgets = {'info': forms.Textarea(attrs={'cols': 50})}
		
class UserForm(forms.ModelForm):
	password = forms.CharField(widget = forms.PasswordInput())
	
	class Meta:
		model = User
		fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		fields = ('picture',)

glasuntu/views.py
from django.shortcuts import render #render function is responsible for rendering the info in the views
from django.core.urlresolvers import reverse
from django.db.models import Q
from .models import VenuePage
from .models import Event
from .models import Genre
from .models import ArtistPage
from .forms import ArtistPageForm, VenuePageForm, UserForm, UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
def index(request):
	"""Glasgow Untuned home page"""
	events = Event.objects.order_by('date')
	genres = Genre.objects.order_by('name')
	venues = VenuePage.objects.order_by('-likes')[:5]
	context_dict = {
		"events":events,
		"genres":genres,
                "venues":venues
	}
	
	return render (request, 'glasuntu/index.html', context_dict)

	
def search(request):
	#retrieve user's query (q) and the desired search type (s)
	query = request.GET.get("q")
	search_type = request.GET.get("s") #search_type will contain "value" attribute of selected <option>
	queries = ""
	view = ""
	
	#get data depending on contents of <select> menu in base.html
	if search_type == "v":
		queries = VenuePage.objects.filter(
			Q(name__icontains=query)
		)
		view = "venue"	
	elif search_type == "a":
		queries = ArtistPage.objects.filter(
			Q(name__icontains=query)
		)
		view = "artist"
		
	context_dict = {
		"queries":queries,
		"view":view,
	}
	
	return render (request, "glasuntu/list.html", context_dict)
	
def venue(request, venue_id):
	venue = VenuePage.objects.get(id=venue_id)
	venueName = venue.name
	events = Event.objects.filter(venue=venue)
	id = venue.id
	context_dict = {
		"venue":venue,
		"events":events,
		"id":id,
                "uID":request.user.id,
                "ownerID":venue.owner.id,
	}
	
	return render(request, 'glasuntu/venue.html', context_dict)
	
def artist(request, artist_id):
	artist = ArtistPage.objects.get(id=artist_id)
	artistName = artist.name
	id = artist.id
	events = Event.objects.filter(name=artist)
	context_dict = {
		"artist":artist,
		"id":id,
                "events":events,
                "uID":request.user.id,
		"ownerID":artist.owner.id,
	}
	
	return render(request, 'glasuntu/band.html', context_dict)
	
@login_required
def new_artist(request):
	if request.method != 'POST':
		form = ArtistPageForm()
	else:
		form = ArtistPageForm(data = request.POST)
		if form.is_valid():
			new_artist = form.save(commit=False)
			new_artist.owner = request.user
			new_artist.save()
			
	context_dict = {'form':form}
	return render(request, 'glasuntu/new_artist.html', context_dict)
	
@login_required
def new_venue(request):
	if request.method != 'POST':
		form = VenuePageForm()
	else:
		form = VenuePageForm(data = request.POST)
		if form.is_valid():
			new_venue = form.save(commit=False)
			new_venue.owner = request.user
			new_venue.save()
			
	context_dict = {'form':form}
	return render(request, 'glasuntu/new_venue.html', context_dict)
	
def edit_artist(request, artist_id):
	artist = ArtistPage.objects.get(id=artist_id)
	info = artist.info
	
	if request.method != 'POST':
		form = ArtistPageForm(instance=artist)
	else:
		form = ArtistPageForm(instance=artist, data=request.POST)
		if form.is_valid():
			form.save()
			
	context_dict = {'artist':artist, 'info':info, 'form':form, 'id':artist_id}
	return render(request, 'glasuntu/edit_artist.html', context_dict)

def edit_venue(request, venue_id):
	venue = VenuePage.objects.get(id=venue_id)
	info = venue.info
	
	if request.method != 'POST':
		form = VenuePageForm(instance=venue)
	else:
		form = VenuePageForm(instance=venue, data=request.POST)
		if form.is_valid():
			form.save()
			
	context_dict = {'venue':venue, 'info':info, 'form':form, 'id':venue_id}
	return render(request, 'glasuntu/edit_venue.html', context_dict)
	
def register(request):
	registered = False
	
	if request.method == "POST":
		user_form = UserForm(data=request.POST)
		profile_form = UserProfileForm(data=request.POST)
		
		if user_form.is_valid() and profile_form.is_valid():
			user = user_form.save()
			user.set_password(user.password)
			user.save()
		
			profile = profile_form.save(commit=False)
			profile.user = user
		
			if 'picture' in request.FILES:
				profile.picture = request.FILES['picture']
				
			profile.save()
		
			registered = True
		else:
			print(user_form.errors, profile_form.errors)
	else:
		user_form = UserForm()
		profile_form = UserProfileForm()
		
	return render(request,
        'glasuntu/register.html',
        {'user_form': user_form,
        'profile_form': profile_form,
        'registered': registered})
		
def user_login(request):
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')

		user = authenticate(username=username, password=password)

		if user:
			if user.is_active:
				login(request, user)
				return HttpResponseRedirect(reverse('glasuntu:index'))
			else:
				return HttpResponse("Your Glasgow Untuned account is disabled.")
		else:
			print("Invalid login details: {0}, {1}".format(username, password))
			return HttpResponse("Invalid login details supplied.")

	else:
		return render(request, 'glasuntu/login.html', {})
		
@login_required
def user_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse('glasuntu:index'))


@login_required
def like_venue(request):
        ven_id=None
        if request.method == 'GET':
                ven_id = request.GET['venue_id']
        likes=0
        if ven_id:
                ven = VenuePage.objects.get(id=int(ven_id))
                if ven:
                        likes = ven.likes + 1
                        ven.likes = likes
                        ven.save()
        return HttpResponse(likes)

glasuntu/templates/glasuntu/band.html
{% extends "glasuntu/base.html" %}

<head>
	<title>{{ artist }}</title>
</head>

{% block head %}
{% endblock head %}

{% block content %}

<body>
	<h2> {{ artist }} </h2>
	</br>
	{% if user.is_authenticated %}
			{% if uID == ownerID %}
				<a href="{% url 'glasuntu:edit_artist' id %}">edit</a>
			{% else %}
				<p></p>
			{% endif %}
		{% else %}
			<p></p>
	{% endif %}

	<div class = "row">
		<div class="column"><a href="{{ artist.website }}">Website</a></div>
		<div class="column">Genre: {{ artist.genre }}</div>
	</div>

	<div class = "pic">
		<div class="left-element">
			<img src="{{artist.picture}}"
			alt="pic" width="1000" height="700"/>
		</div>

		<div class="mid-element">
			<h2>About</h2>
			<p>{{ artist.info }}</p>
		</div>

		<div class="right-element">
		<h2>Upcoming Gigs</h2>
				<p>
				<ul>
					{% for event in events %}
							<li>{{ event.venue }} on {{ event.date }}</li>
					{% empty %}
						<li>{{ artist }} has no gigs scheduled.</li>
					{% endfor %}
				</ul>
				</p>
		</div>
	</div>
{% endblock content %}
</body>

glasuntu/templates/glasuntu/base.html
{% load static %}
{% load bootstrap3 %}

<!DOCTYPE html>


<html lang = "en">
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content = "IE-edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel = "stylesheet" href = "/static/glasuntu/custom.css">
	<link rel = "stylesheet" href = "/static/glasuntu/ven.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
	<script src="{% static 'glasuntu/jquery-3.3.1.js' %}"></script>
	<script src="{% static 'glasuntu/jquery.min.js' %}"></script>
	<script src="{% static 'glasuntu/fb.js' %}"></script>
	<script src="{% static 'glasuntu/glasajax.js' %}"></script>
	{% bootstrap_css %}
	{% bootstrap_javascript %}

	</head>

	<body>
	<nav class = "navbar navbar-default navbar-static-top">
		<button class = "navbar-toggle collapsed">
			data-toggle="collapse" data-target="#navbar"
			aria-controls="navbar" aria-expanded="false"
			aria-label="toggle nav">
			<span class = "navbar-toggler-icon"></span>
		</button>

		<a href="{% url 'glasuntu:index' %}" class = "navbar-brand">Glasgow Untuned</a>

		<form method = "GET" action = "{% url 'glasuntu:search' %}" class = "navbar-form navbar-left" id = "navSearch">

			<label for="search_options" id = "label">Search by:</label>

			<!--Content of the selection menu is retrieved in "search" view-->
			<select id = "search_options" name = "s" value = "{{ request.GET.s }}"/>
				<option value = "a">Artist</option>
				<option value = "v">Venue</option>
			</select>

			<!-- "q" = the user's query -->
			<input id = "search" name = "q" type = "text" placeholder = "Search..." value = "{{ request.GET.q }}"/>
			<input id = "searchButt" type = "submit" value = "Submit"/>
		</form>

		<ul class="nav navbar-nav navbar-right">
			<li><a href = "{% url 'glasuntu:new_artist' %}" id = "navRight" >Create an Artist Page</a></li>
			<li><a href = "{% url 'glasuntu:new_venue' %}" id = "navRight">Register Your Venue</a></li>
			{% if user.is_authenticated %}
				<li><a href="{% url 'auth_logout' %}" id = "navRight">Logout</a></li>
			{% else %}
				<li><a href="{% url 'registration_register' %}" id = "navRight">Sign Up</a></li>
				<li><a href="{% url 'auth_login' %}" id = "navRight">Sign In</a></li>
			{% endif %}
		</ul>
	</nav>

	{% block header %}{% endblock header %}

	<!--content of the block is determined in the inheriting template-->
	{% block content %}{% endblock content %}

	</body>

	<footer>
		<div id = "foot">

			<!--<p id = "social">Facebook and Twitter links<p>-->
			<!--<p id = "contact">Contact us: 2088324M@student.gla.ac.uk<p>-->
			<!--<p id = "faq">FAQ</p>-->

		</div>
	</footer>
</html>

glasuntu/templates/glasuntu/edit_artist.html
{% extends "glasuntu/base.html" %}

{% block content %}

<p>Edit Artist Information</p>
<form action = "{% url 'glasuntu:edit_artist' id %}" method='post'>
	{% csrf_token %}
	{{ form.as_p }}
	<button name="submit">Save</button>
</form>

{% endblock content %}

glasuntu/templates/glasuntu/edit_venue.html
{% extends "glasuntu/base.html" %}

{% block content %}

<p>Edit Venue Information</p>
<form action = "{% url 'glasuntu:edit_venue' id %}" method='post'>
	{% csrf_token %}
	{{ form.as_p }}
	<button name="submit">Save</button>
</form>

{% endblock content %}

glasuntu/templates/glasuntu/index.html
{% extends "glasuntu/base.html" %}

<head>
	<title>Glasgow Untuned Homepage</title>
	<meta name = "authors" content = "Matthew Murray, Jamie Howitt, Jamie Dickson">
	<meta name = "page description" content = "This is the homepage of Glasgow Untuned, a site for discovering music venues and upcoming performances">
</head>

{% block header %}
<head>
	<title>Glasgow Untuned Homepage</title>
	<meta name = "authors" content = "Matthew Murray, Jamie Howitt, Jamie Dickson">
	<meta name = "page description" content = "This is the homepage of Glasgow Untuned, a site for discovering music venues and upcoming performances">
</head>
<!--
<form method = "POST" action = "">
	<input id = "uEnt" type = "text" placeholder = "Username">
	<input id = "pEnt" type = "text" placeholder = "Password">
	<input id = "loginButt" type = "submit" value = "Login">
</form>
-->

<div class = "jumbotron">
	<h1>Welcome to Glasgow Untuned</h1>
</div>
{% endblock header %}

{% block content %}
<body>
	<div class = "col-md-6" id = "upcoming">
		<h2>Upcoming Events</h2>
			<nav id = "EventsNav">
				<ul>
					{% for event in events %}
						<li><a href="{% url 'glasuntu:artist' event.name.id %}">{{ event.name.name }}</a> at <a href="{% url 'glasuntu:venue' event.venue.id %}">{{event.venue}}</a></li>
					{% empty %}
						<li>No events are scheduled yet.</li>
					{% endfor %}
				</ul>
			</nav>
	</div>

	<div class = "col-md-6" id = "recent">
		<h2>Most Liked Venues</h2>
			<nav id = "RecentNav">
				<ul>
					{% for venue in venues %}
						<li><a href="{% url 'glasuntu:venue' venue.id %}">{{ venue.name }}</a></li>
					{% empty %}
						<li>There are no liked venues.</li>
					{% endfor %}
				</ul>
			</nav>
	</div>


</body>

{% endblock content %}

glasuntu/templates/glasuntu/list.html
{% extends "glasuntu/base.html" %}

{% block head %}
	<input id = "uEnt" type = "text" placeholder = "Username">
	<input id = "pEnt" type "text" placeholder = "Password">
{% endblock head %}

{% block content %}

<body>
	
	<div class = "jumbotron">
		<h1>Search Results</h1>
	</div>
	
	<ul>
		{% for query in queries %}
			<div class="panel panel-default">
					{% if view == "venue" %}
						<div class = "panel-heading">
							<h3>
								<li><a href = "{% url 'glasuntu:venue' venue_id=query.id %}">{{ query }}</a></li>
							</h3>
						</div>
					{% else %}
						<div class = "panel-heading">
							<h3>
								<li><a href = "{% url 'glasuntu:artist' artist_id=query.id %}">{{ query }}</a></li>
							</h3>
						</div>
			</div>
			{% endif %}
		{% empty %}
			<p><em>No matches found.</em></p>
		{% endfor %}
	</ul>

{% endblock content %}

glasuntu/templates/glasuntu/new_artist.html
{% extends "glasuntu/base.html" %}

{% block content %}

	<p>Create your artist page:</p>
	
	<form action = "{% url 'glasuntu:new_artist' %}" method='post'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">Create Page</button>
	</form>

{% endblock content %}

glasuntu/templates/glasuntu/new_venue.html
{% extends "glasuntu/base.html" %}

{% block content %}

	<p>Register your venue:</p>
	
	<form action = "{% url 'glasuntu:new_venue' %}" method='post'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">Create Page</button>
	</form>

{% endblock content %}

glasuntu/templates/glasuntu/venue.html
{% extends "glasuntu/base.html" %}

<head>
	<title>{{ venue }}</title>
</head>

.body{
	overflow:scroll;
}

{% block content %}
<body>
<div id = "fb-root"></div>

	<main role="main">

		<div>
			<h2> {{ venue }} </h2>
		</div>



	<div class="row">
		<!--<div class = "column"><a href="{% url 'glasuntu:edit_venue' id %}">edit</a></div>-->
		<div class="column"><strong id="like_count">{{ venue.likes }}</strong> people like this venue.</div>
		<div class="column">{% if user.is_authenticated %}
			<button id="likes" data-venid="{{venue.id}}"
				class="btn btn-primary btn-sm" typer="button">
				Like</button>
			{% endif %}</div>
		<div class="column"><a href="{{ venue.website }}">Visit Their Website</a></div>
		<div class="column"> <p>{{venue.address}}</p></div>
		<div class="column">Genre: {{ venue.genre }}</div>
	</div>
	{% if user.is_authenticated %}
			{% if uID == ownerID %}
				<a href="{% url 'glasuntu:edit_venue' id %}">edit</a>
			{% else %}
				<p></p>
			{% endif %}
		{% else %}
			<p></p>
		{% endif %}
	</main>

	<div class="pic">
		<div class="left-element">
			<img src="{{venue.picture}}"
			alt="pic" width="1150" height="900"/>
		</div>

		<div class="mid-element">
			<div class="mid-top">
				<h2>About</h2>
				<p>{{ venue.info }}</p>

			<div class="mid-bottom">
				<h2>Upcoming Events</h2>
				<p>
				<ul>
					{% for event in events %}
						<li>{{ event.name.name }} on {{ event.date }}</li>
					{% empty %}
						<li>{{ venue.name}} has no gigs scheduled.</li>
					{% endfor %}
				</ul>
				</p>
			</div>
			</div>
		</div>

		<div class="right-element">
			<div class="fb-comments" data-href="{{ request.build_absolute_url }}" data-numposts="5"></div>
		</div>
	</div>
	{% endblock content %}
  </body>